### ISSUE TITLE
Increment and decrement overclock value buttons don't work properly

### ISSUE THREAD

**Issue by RnDMonkey** [KirkMcDonald/satisfactory-calculator#13] opened 2019-04-01 02:06 UTC
The increment and decrement buttons, aside from being quite small, don't seem to allow more than one single click between movements of the mouse i.e. you must click, move the mouse slightly, then click again. Click and hold works as expected, though it's a bit less useful without the calculations updating live so you know about when to release.

**Comment by KirkMcDonald** [comment] 2019-04-01 06:58
I know the cause of this, at least: Each time you change that value, it recomputes the solution, which causes it to re-render the whole page. The element you click on the first time is an entirely different element than the one you click on the second time.

It is worth noting that this problem does not occur in Firefox.

I had this same problem in the Factorio calculator, and the solution here is the same as what I did there: Make the elements persistent when possible, and update their values, rather than regenerating the whole thing every time. I implemented it this way first (both times) because it is much more expedient.

**Comment by KirkMcDonald** [comment] 2019-04-02 01:39
It turns out this wasn't *quite* as painful as I thought it would be. Score one for d3. Fixed in ba048b624c4448312606765b5cb28d2a84a0cfe6.

**Closed by KirkMcDonald** 2019-04-02 01:39 UTC

**Comment by RnDMonkey** [comment] 2019-04-03 03:42
I am using Chrome. I notice that the buttons now affect the input number upon successive clicks, but the solution does not update until a mouse move followed by another click. The mouse doesn't have to leave the button entirely now, which is nice, but it still requires a little "wiggle". Is it possible to recalculate just the item page's numbers on every input value change without incurring updates that require redrawing the page?

**Comment by KirkMcDonald** [comment] 2019-04-03 04:27
971e01c96ae830ff9c53ee2103d05ce097463ef7 changes the input from using a ["change" event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) to using an ["input" event](https://developer.mozilla.org/en-US/docs/Web/Events/input), which will take effect more frequently.

However, it is worth noting that these arrows are merely the browser's native arrows from using an `<input>` field with `type="number"`. There is apparently [an outstanding bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=419108) which affects such fields; there isn't much I can do about that.

**Comment by RnDMonkey** [comment] 2019-04-03 07:53
I wasn't seeing anything related to that Chrome bug you linked, as far as I can tell. Update #971e01c seems to have fixed every issue I saw and it's working as expected now.
